# Generated by Django 4.1.3 on 2022-12-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_remove_profile_full_name_profile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='first_name',
        ),
    ]
