# Generated by Django 4.1.3 on 2022-12-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
