# Generated by Django 4.1.3 on 2022-12-12 04:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0007_alter_message_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('project_image', models.ImageField(blank=True, default='projects/default_project_image.png', null=True, upload_to='', verbose_name='Изображение проекта')),
                ('link_github', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на гитхаб')),
                ('like_total', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.profile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['like_total', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_body', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('value', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyqt_app.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.profile')),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
