# Generated by Django 4.1.3 on 2022-12-17 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyqt_app', '0002_alter_project_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-like_total', '-created'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
