# Generated by Django 4.1.3 on 2022-12-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyqt_app', '0004_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
