# Generated by Django 4.1.3 on 2022-12-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_message_first_name'),
        ('pyqt_app', '0005_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'project')},
        ),
    ]
