# Generated by Django 4.1.3 on 2022-12-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqt_app', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='projects/default_project_image.png', null=True, upload_to='projects/', verbose_name='Изображение проекта'),
        ),
    ]
